# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def shared_pods
  pod 'RealmLoginKit/AWSCognito', :path => 'RealmLoginKit.podspec'

  # Client-side component of http://revealapp.com used for UI debugging
  # pod 'Reveal-SDK', :configurations => ['Debug']
end 

target 'RealmLoginKitExample' do
  use_frameworks!
  shared_pods
end

target 'RealmLoginKit' do
  use_frameworks!
  shared_pods
end

target 'RealmLoginKitExampleTests' do
  use_frameworks!
  shared_pods
end
