platform :ios, '9.0'

target 'RealmLoginKitExample-tvOS' do
  platform :tvos, '9.0'
  use_frameworks!
  pod 'Realm'
end

target 'RealmLoginKitExample-iOS' do
  use_frameworks!
  pod 'Realm'
  pod 'TORoundedTableView'
end

target 'RealmLoginKit' do
  use_frameworks!
  pod 'TORoundedTableView'
  pod 'Realm'
end